const tests = [
  ['localization catalogs and stable display mappings', require('./localization.test.js')],
  ['locale resolution and device preference', require('./locale-service.test.js')],
  ['local backup settlement', require('./local-backup-settlement.test.js')],
  ['cloud backup cadence and stale acknowledgements', require('./cloud-backup-service.test.js')],
  ['cloud backup restore and conflicts', require('./cloud-backup-restore.test.js')],
  ['cloud identity client persistence and races', require('./cloud-identity-client.test.js')],
  ['cloud environment scopes', require('./cloud-environment-scope.test.js')],
  ['cloud read-only state isolation', require('./cloud-readonly-state.test.js')],
  ['cloud account scopes', require('./cloud-account-scope.test.js')],
  ['cloud local migration and authoritative safety', require('./cloud-session-migration.test.js')],
  ['cloud stale callbacks', require('./cloud-stale-callback.test.js')],
  ['cloud function transport', require('./cloud-function-transport.test.js')],
  ['cloud partial ACK and pending overlay', require('./cloud-sync-partial-ack.test.js')],
  ['cloud economy purchase retry', require('./cloud-economy-purchase.test.js')],
  ['cloud new-device core restore', require('./cloud-new-device-restore.test.js')],
  ['cloud stage 5 stamina and preferences', require('./cloud-stage5-client.test.js')],
  ['cloud local-first checkpoint sync and request counts', require('./cloud-checkpoint-sync.test.js')],
  ['cloud settlement mode bootstrap routing', require('./cloud-mode-routing.test.js')],
  ['single settlement bootstrap composition', require('./single-settlement-bootstrap.test.js')],
  ['cloud rollout admission and first save', require('./cloud-rollout.test.js')],
  ['stage 4 private client backup', require('./stage4-client-backup.test.js')],
  ['stage 4 synthetic legacy save', require('./stage4-synthetic-save.test.js')],
  ['cloudbase disabled local behavior', require('./cloudbase-disabled.test.js')],
  ['production release readiness', require('./release-readiness.test.js')],
  ['cloud runtime config selection', require('./cloud-runtime-config.test.js')],
  ['level records, gallery navigation and beginner instructions', require('./level-ui.test.js')],
  ['stamina service', require('./stamina-service.test.js')],
  ['stamina app', require('./stamina-app.test.js')],
  ['stamina renderer', require('./stamina-renderer.test.js')],
  ['tiered daily hint unlocks', require('./hint-tiered.test.js')],
  ['daily hint access', require('./hint-access-service.test.js')],
  ['hint share unlock flow', require('./hint-share.test.js')],
  ['reward service', require('./reward-service.test.js')],
  ['reward unlock service', require('./reward-unlock-service.test.js')],
  ['reward unlock app', require('./reward-unlock-app.test.js')],
  ['reward unlock renderer', require('./reward-unlock-renderer.test.js')],
  ['shared result panel style', require('./result-panel-style.test.js')],
  ['daily authorized entry grants', require('./daily-entry-grant.test.js')],
  ['share service', require('./share-service.test.js')],
  ['share entry lifecycle', require('./share-entry.test.js')],
  ['profile service', require('./profile-service.test.js')],
  ['account layout', require('./account-layout.test.js')],
  ['account app', require('./account-app.test.js')],
  ['account offline bootstrap', require('./account-bootstrap.test.js')],
  ['progress sync conflicts', require('./progress-sync-conflict.test.js')],
  ['session store', require('./session-store.test.js')],
  ['sync store', require('./sync-store.test.js')],
  ['api client', require('./api-client.test.js')],
  ['auth service', require('./auth-service.test.js')],
  ['progress sync service', require('./progress-sync-service.test.js')],
  ['behavior service', require('./behavior-service.test.js')],
  ['engagement service', require('./engagement-service.test.js')],
  ['level Copilot contracts', require('./level-copilot-contracts.test.js')],
  ['level Copilot candidate validation', require('./level-copilot-candidate.test.js')],
  ['level Copilot deterministic validator', require('./level-copilot-validator.test.js')],
  ['level Copilot Responses client', require('./level-copilot-client.test.js')],
  ['level Copilot Codex CLI client', require('./level-copilot-codex-client.test.js')],
  ['level Copilot pipeline and run store', require('./level-copilot-pipeline.test.js')],
  ['level Copilot evaluation metrics', require('./level-copilot-eval.test.js')],
  ['architecture boundaries', require('./architecture-boundaries.test.js')],
  ['game runner', require('./game-runner.test.js')],
  ['ice mechanic and isolated 5x5 trial', require('./ice-trial.test.js')],
  ['ice mainline teaching, hints and ordinary settlement', require('./ice-mainline.test.js')],
  ['ten-level thaw pack, multi-ice coverage and difficulty transitions', require('./thaw-pack.test.js')],
  ['twenty-level meadow pack, limited ice and one challenge peak', require('./meadow-pack.test.js')],
  ['game runner contract', require('./game-runner-contract.test.js')],
  ['run context and completion policies', require('./run-context.test.js')],
  ['progress store', require('./progress-store.test.js')],
  ['preferences service', require('./preferences-service.test.js')],
  ['clear effect service', require('./clear-effect-service.test.js')],
  ['clear effect system', require('./clear-effect-system.test.js')],
  ['canvas renderer', require('./renderer.test.js')],
  ['canvas button labels', require('./renderer-button.test.js')],
  ['interaction map', require('./interaction-map.test.js')],
  ['board input controller', require('./board-input-controller.test.js')],
  ['mini game app smoke', require('./app-smoke.test.js')],
  ['ads service', require('./ads-service.test.js')],
  ['skin service', require('./skin-service.test.js')],
  ['WeChat project config', require('./project-config.test.js')],
  ['compiled level modules', require('./level-modules.test.js')],
  ['progression service', require('./progression-service.test.js')],
  ['developer tools runtime gate', require('./devtools-runtime.test.js')],
  ['audio service', require('./audio-service.test.js')],
  ['hint service', require('./hint-service.test.js')],
  ['solutions', require('./solutions.test.js')],
  ['theme system', require('./theme-system.test.js')],
  ['subpackage service', require('./subpackage-service.test.js')],
  ['package budget', require('./package-budget.test.js')],
  ['theme assets', require('./theme-assets.test.js')],
  ['gallery preview assets', require('./gallery-preview-assets.test.js')],
  ['daily challenge service', require('./daily-challenge-service.test.js')],
  ['daily progress store', require('./daily-progress-store.test.js')],
  ['daily progress adapter', require('./daily-progress-adapter.test.js')],
  ['daily ViewModel mapping', require('./daily-view-model.test.js')],
  ['daily app flow', require('./daily-app.test.js')],
  ['portal validation', require('./portal-validation.test.js')],
  ['game runner portals', require('./game-runner-portal.test.js')],
  ['hint service portals', require('./hint-service-portal.test.js')],
  ['app portals', require('./app-portal.test.js')],
  ['renderer portals', require('./renderer-portal.test.js')],
  ['gameplay mechanics', require('./mechanics.test.js')],
  ['portal publishing gate', require('./portal-publishing.test.js')],
  ['mixed 8x8 chapter', require('./mixed-chapter.test.js')],
  ['8x8 design difficulty, recovery pack and stable navigation', require('./level-difficulty.test.js')]
];

async function main() {
  let failed = 0;
  for (const [name, test] of tests) {
    try {
      await test();
      console.log(`PASS ${name}`);
    } catch (error) {
      failed++;
      console.error(`FAIL ${name}`);
      console.error(error.stack || error);
    }
  }
  if (failed) process.exit(1);
}

main();
